name: 이슈 템플릿
title: '[] '
description: 기능 구현, 버그 수정, 문서화 등

body:
  - type: textarea
    id: feature-contents
    attributes:
      label: 📄 설명
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    id: todo-list
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
      placeholder: 최대한 세분화 해서 적어주세요!
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
      placeholder: ex. 참고 자료 url
    validations:
      required: false
